M48
; DRILL file KiCad 10.0.3 date 2026-07-20T14:37:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-20T14:37:06+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X147.32Y-93.98
X147.32Y-96.48
T2
X127.0Y-86.36
X127.0Y-91.36
X127.0Y-96.36
M30
